### ISSUE TITLE
update `chai.js` to current version to be able to `use strict` mode

### ISSUE THREAD

**Issue by Kosta-Github** [victorquinn/memcache-plus#42]
please, either:
* update `chai.js` dep to current version so that we can use your lib with `use strict` mode, or
* get rid of the `chai.js` dep (which is a heavy/large lib not meant to be used in production, IMHO) in your lib completely and re-impl the few `assert` checks on your own (preferred)

**Comment by victorquinn** [comment]
Fixed with #44
