### ISSUE TITLE
Unix domain socket connection(IPC) support

### ISSUE THREAD

**Issue by RomanBurunkov** [victorquinn/memcache-plus#78]
Hi there,

Is it possible to connect to the memcached configured to work via unix socket?

I can't see any details whether it is possible in docs.
Also tried to specify path to socket in host option like this:

```
hosts: ['/var/run/memcached/memcached.sock:0']
```

but got an error:

```
Error: getaddrinfo ENOTFOUND /var/run/memcached/memcached.sock
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '/var/run/memcached/memcached.sock'
}
```

**Comment by RomanBurunkov** [comment]
From the sources it looks that port always specified for net.connect method.

So it looks that current version doesn't support unix socket connections.

My suggestion is in case port options set to 0 do not specify options object and just specify a host param for connect method so it will try to connect via IPC instead of network.

See connect method spec:

```
net.connect(path[, connectListener]) for IPC connections.
```

**Comment by victorquinn** [comment]
Don't think it's possible today, but happy to accept a PR for this!

**Comment by RomanBurunkov** [comment]
Hi Victor,

I've created a PR #80  for that feature.
Please review it, will happy if it will be merged and published.

Thanks.
